# Generated by Django 5.0.3 on 2024-09-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('dpi', models.CharField(max_length=13)),
            ],
        ),
    ]
