# Generated by Django 5.1.1 on 2024-10-01 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directora', '0005_notificacion_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='asignada_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='directora.empleado'),
        ),
    ]
