# Generated by Django 5.1.1 on 2024-10-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directora', '0007_alter_tarea_asignada_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='asignada_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directora.empleado'),
        ),
    ]
